# Generated by Django 4.2.7 on 2023-12-01 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VotingAdmin', '0002_survey_choice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
    ]
